--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO neondb_owner;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO neondb_owner;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO neondb_owner;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO neondb_owner;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO neondb_owner;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO neondb_owner;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO neondb_owner;

--
-- Name: flight_app_auditlog; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.flight_app_auditlog (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    details jsonb,
    "timestamp" timestamp with time zone NOT NULL,
    ip_address inet,
    user_id bigint NOT NULL
);


ALTER TABLE public.flight_app_auditlog OWNER TO neondb_owner;

--
-- Name: flight_app_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.flight_app_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_app_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_app_division; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.flight_app_division (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    code character varying(3) NOT NULL
);


ALTER TABLE public.flight_app_division OWNER TO neondb_owner;

--
-- Name: flight_app_division_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.flight_app_division ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_app_division_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_app_flightdata; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.flight_app_flightdata (
    id bigint NOT NULL,
    date date NOT NULL,
    flight_number character varying(20) NOT NULL,
    aircraft_registration character varying(20),
    flight_crew jsonb,
    sn_crew character varying(100),
    cabin_crew jsonb,
    afl_number character varying(20),
    from_location character varying(100),
    to_location character varying(100),
    air_time_hrs integer,
    air_time_mins integer,
    block_time_hrs integer,
    block_time_mins integer,
    fuel_uplift_liters double precision,
    sp_gravity double precision,
    temp_celsius double precision,
    fuel_added_kg double precision,
    total_fuel_tons double precision,
    fuel_burnt_tons double precision,
    remaining_fuel_tons double precision,
    mail_kg double precision,
    cargo_kg double precision,
    pax integer,
    weight_kg double precision,
    remarks text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    division_id bigint NOT NULL
);


ALTER TABLE public.flight_app_flightdata OWNER TO neondb_owner;

--
-- Name: flight_app_flightdata_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.flight_app_flightdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_app_flightdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_app_user; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.flight_app_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_first_login boolean NOT NULL,
    division_id bigint
);


ALTER TABLE public.flight_app_user OWNER TO neondb_owner;

--
-- Name: flight_app_user_groups; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.flight_app_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.flight_app_user_groups OWNER TO neondb_owner;

--
-- Name: flight_app_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.flight_app_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_app_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.flight_app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_app_user_user_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.flight_app_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.flight_app_user_user_permissions OWNER TO neondb_owner;

--
-- Name: flight_app_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.flight_app_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_app_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add division	6	add_division
22	Can change division	6	change_division
23	Can delete division	6	delete_division
24	Can view division	6	view_division
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add audit log	8	add_auditlog
30	Can change audit log	8	change_auditlog
31	Can delete audit log	8	delete_auditlog
32	Can view audit log	8	view_auditlog
33	Can add flight data	9	add_flightdata
34	Can change flight data	9	change_flightdata
35	Can delete flight data	9	delete_flightdata
36	Can view flight data	9	view_flightdata
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-04-18 08:59:54.64595+00	2	foi (FOI)	1	[{"added": {}}]	7	1
2	2025-04-18 09:05:55.09159+00	3	oep (OEP)	1	[{"added": {}}]	7	1
3	2025-04-18 09:10:38.841957+00	4	ccd (CCD)	1	[{"added": {}}]	7	1
4	2025-04-19 15:00:01.364219+00	3	oep (OEP)	2	[{"changed": {"fields": ["password"]}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	flight_app	division
7	flight_app	user
8	flight_app	auditlog
9	flight_app	flightdata
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-18 08:52:51.173188+00
2	contenttypes	0002_remove_content_type_name	2025-04-18 08:54:19.45035+00
3	auth	0001_initial	2025-04-18 08:54:19.794568+00
4	auth	0002_alter_permission_name_max_length	2025-04-18 08:54:19.859063+00
5	auth	0003_alter_user_email_max_length	2025-04-18 08:54:19.902327+00
6	auth	0004_alter_user_username_opts	2025-04-18 08:54:19.961181+00
7	auth	0005_alter_user_last_login_null	2025-04-18 08:54:20.020021+00
8	auth	0006_require_contenttypes_0002	2025-04-18 08:54:20.121847+00
9	auth	0007_alter_validators_add_error_messages	2025-04-18 08:54:20.180321+00
10	auth	0008_alter_user_username_max_length	2025-04-18 08:54:20.238831+00
11	auth	0009_alter_user_last_name_max_length	2025-04-18 08:54:20.298237+00
12	auth	0010_alter_group_name_max_length	2025-04-18 08:54:20.39454+00
13	auth	0011_update_proxy_permissions	2025-04-18 08:54:20.435018+00
14	auth	0012_alter_user_first_name_max_length	2025-04-18 08:54:20.505787+00
15	flight_app	0001_initial	2025-04-18 08:54:21.208435+00
16	admin	0001_initial	2025-04-18 08:54:21.37565+00
17	admin	0002_logentry_remove_auto_add	2025-04-18 08:54:21.40233+00
18	admin	0003_logentry_add_action_flag_choices	2025-04-18 08:54:21.466672+00
19	sessions	0001_initial	2025-04-18 08:54:21.629202+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
d7355wrywcbpx9koioqryp5in0fck4v7	.eJxVjDsOwjAQBe_iGln-xR9K-pzBWnvXOIAcKU4qxN1JpBTQvpl5bxZhW2vcOi1xQnZlml1-twT5Se0A-IB2n3me27pMiR8KP2nn44z0up3u30GFXvfaK52peChoA2BKg0Wpk5IlCOO0IiDrTTBBaDtIIOd2LpQzhIRaOsU-X_D9N6k:1u69n9:XbP5PP_fywV1qb8bA2F6eHMdY2rLIfQeTDE6bIKlQ_o	2025-05-03 15:07:39.449037+00
vkndxkxif2yeu5qu7jnd0xz5xu8o5zje	.eJxVjMsOwiAURP-FtSHAxUBduvcbCPeBVA1NSrsy_rtt0oUuZ86ZeauU16WmtcucRlYXZdXpt8NMT2k74Edu90nT1JZ5RL0r-qBd3yaW1_Vw_w5q7nVbQzQgDpkAvRd7jqHEwUdbkNEYLi5aIF-2bAI4CugiekISEQg5DOrzBeXMOFw:1u6ACb:cqjjli36qmL2b1FexrEU5uP5SpC82OmaaITwDJb0Ob0	2025-05-03 15:33:57.87009+00
\.


--
-- Data for Name: flight_app_auditlog; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.flight_app_auditlog (id, action, details, "timestamp", ip_address, user_id) FROM stdin;
1	LOGIN	\N	2025-04-18 08:57:09.680775+00	113.199.192.51	1
2	LOGOUT	\N	2025-04-18 09:01:15.768941+00	113.199.192.51	1
3	LOGIN	\N	2025-04-18 09:01:26.580257+00	113.199.192.51	2
4	PASSWORD	\N	2025-04-18 09:02:14.256056+00	113.199.192.51	2
5	CREATE	{"date": "2025-04-18", "division": "FOI", "flight_number": "RA217"}	2025-04-18 09:03:14.096851+00	\N	2
6	CREATE	{"date": "2025-04-18", "division": "FOI", "flight_number": "RA217"}	2025-04-18 09:03:14.116155+00	113.199.192.51	2
7	EDIT	{"date": "2025-04-18", "changes": {"sn_crew": {"new": "SB,RKS", "old": "-"}}, "division": "FOI", "flight_number": "RA217"}	2025-04-18 09:03:38.722011+00	113.199.192.51	2
8	LOGOUT	\N	2025-04-18 09:03:49.655065+00	113.199.192.51	2
9	LOGIN	\N	2025-04-18 09:04:07.895476+00	113.199.192.51	1
10	LOGIN	\N	2025-04-18 09:06:24.107691+00	113.199.192.51	3
11	PASSWORD	\N	2025-04-18 09:06:45.512061+00	113.199.192.51	3
12	CREATE	{"date": "2025-04-18", "division": "OEP", "flight_number": "RA217"}	2025-04-18 09:07:56.803703+00	\N	3
13	CREATE	{"date": "2025-04-18", "division": "OEP", "flight_number": "RA217"}	2025-04-18 09:07:56.824062+00	113.199.192.51	3
14	LOGOUT	\N	2025-04-18 09:08:31.060261+00	113.199.192.51	3
15	LOGIN	\N	2025-04-18 09:08:57.16821+00	113.199.192.51	1
16	PASSWORD	\N	2025-04-18 09:09:33.719694+00	113.199.192.51	1
17	LOGIN	\N	2025-04-18 09:10:55.631554+00	113.199.192.51	4
18	CREATE	{"date": "2025-04-18", "division": "CCD", "flight_number": "RA217"}	2025-04-18 09:11:22.207414+00	\N	4
19	CREATE	{"date": "2025-04-18", "division": "CCD", "flight_number": "RA217"}	2025-04-18 09:11:22.224515+00	113.199.192.51	4
20	LOGOUT	\N	2025-04-18 09:16:45.598208+00	113.199.192.51	4
21	LOGIN	\N	2025-04-19 14:49:00.346841+00	103.10.31.23	4
22	EDIT	{"date": "2025-04-18", "changes": {"cabin_crew": {"new": ["asdk", "dfdf", "eeer", "rt", "rt"], "old": ["asdk", "dfdf", "eeer", "rt", "rt", "dd"]}}, "division": "CCD", "flight_number": "RA217"}	2025-04-19 14:52:17.924676+00	103.10.31.23	4
23	EDIT	{"date": "2025-04-18", "changes": {"cabin_crew": {"new": ["asdk", "dfdf", "eeer", "rt", "rt", "asd"], "old": ["asdk", "dfdf", "eeer", "rt", "rt"]}}, "division": "CCD", "flight_number": "RA217"}	2025-04-19 14:57:20.452085+00	103.10.31.23	4
24	LOGOUT	\N	2025-04-19 14:57:29.506663+00	103.10.31.23	4
25	LOGIN	\N	2025-04-19 14:58:44.456847+00	103.10.31.23	1
26	LOGIN	\N	2025-04-19 15:00:16.343373+00	103.10.31.23	3
27	EDIT	{"date": "2025-04-18", "changes": {"pax": {"new": 153, "old": 150}}, "division": "OEP", "flight_number": "RA217"}	2025-04-19 15:00:44.238529+00	103.10.31.23	3
28	LOGOUT	\N	2025-04-19 15:00:54.294011+00	103.10.31.23	3
29	LOGIN	\N	2025-04-19 15:07:39.411881+00	103.10.31.23	3
30	LOGIN	\N	2025-04-19 15:07:40.238477+00	103.10.31.23	3
31	LOGOUT	\N	2025-04-19 15:32:15.384876+00	103.10.31.23	3
32	LOGIN	\N	2025-04-19 15:32:40.146148+00	103.10.31.23	2
33	CREATE	{"date": "2025-04-19", "division": "FOI", "flight_number": "229"}	2025-04-19 15:33:13.807581+00	\N	2
34	CREATE	{"date": "2025-04-19", "division": "FOI", "flight_number": "229"}	2025-04-19 15:33:13.826586+00	103.10.31.23	2
35	LOGOUT	\N	2025-04-19 15:33:22.384977+00	103.10.31.23	2
36	LOGIN	\N	2025-04-19 15:33:57.850936+00	103.10.31.23	1
\.


--
-- Data for Name: flight_app_division; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.flight_app_division (id, name, code) FROM stdin;
1	Flight Operations International	FOI
2	Flight Operations Domestic	FOD
3	Cabin Crew Division	CCD
4	Operations Engineering & Planning Division	OEP
5	Operations Finance	OF
\.


--
-- Data for Name: flight_app_flightdata; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.flight_app_flightdata (id, date, flight_number, aircraft_registration, flight_crew, sn_crew, cabin_crew, afl_number, from_location, to_location, air_time_hrs, air_time_mins, block_time_hrs, block_time_mins, fuel_uplift_liters, sp_gravity, temp_celsius, fuel_added_kg, total_fuel_tons, fuel_burnt_tons, remaining_fuel_tons, mail_kg, cargo_kg, pax, weight_kg, remarks, created_at, updated_at, created_by_id, division_id) FROM stdin;
1	2025-04-18	RA217	AKW	["DRJ", "PK", "SSJ", "SSV", "AM", "ST", "RR"]	SB,RKS	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N		2025-04-18 09:03:14.049898+00	2025-04-18 09:03:38.704012+00	2	1
3	2025-04-18	RA217	AKW	\N	\N	["asdk", "dfdf", "eeer", "rt", "rt", "asd"]	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N		2025-04-18 09:11:22.187328+00	2025-04-19 14:57:20.4273+00	4	3
2	2025-04-18	RA217	\N	\N	\N	\N	1234567	ktm	del	1	22	1	52	1200	0.78	23	850	15.2	5	10.2	0	125	153	68000		2025-04-18 09:07:56.777563+00	2025-04-19 15:00:44.215683+00	3	4
4	2025-04-19	229	AKW	["fg", "gh", "jh", "mn"]	-	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N		2025-04-19 15:33:13.781457+00	2025-04-19 15:33:13.781472+00	2	1
\.


--
-- Data for Name: flight_app_user; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.flight_app_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, is_first_login, division_id) FROM stdin;
4	pbkdf2_sha256$1000000$u6oD28yM3xYSlnjBv1vSIk$fOcOyr1ejEmWJR3/CPGRhuQZKNUGmAZlXdoOyLjrkHw=	2025-04-19 14:49:00.325405+00	f	ccd				f	t	2025-04-18 09:10:38.451591+00	f	3
3	pbkdf2_sha256$1000000$RvKKTrJBVx1uka8Jj6FDuE$HOFIwJUccKdu/VGHG5e1AFbBkShWzOO16YP9duOdVlc=	2025-04-19 15:07:40.21808+00	f	oep				f	t	2025-04-18 09:05:54.657443+00	f	4
2	pbkdf2_sha256$1000000$5OTGhfvAA3R5iEv8GureJZ$FAhrSUB2Gh5TKYTJ4j7sjlhX7Tp7Vo08pi8ivCeOoPY=	2025-04-19 15:32:40.124033+00	f	foi				f	t	2025-04-18 08:59:54.288373+00	f	1
1	pbkdf2_sha256$1000000$mo7TIEELhfxHso7OKlHswi$HsHzZ8UrKjEfb5H5OdqzMlvtd5LV25GhU3Do/Tz8zEs=	2025-04-19 15:33:57.832726+00	t	admin			admin@example.com	t	t	2025-04-18 08:54:23.159818+00	f	\N
\.


--
-- Data for Name: flight_app_user_groups; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.flight_app_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: flight_app_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.flight_app_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 4, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: flight_app_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.flight_app_auditlog_id_seq', 36, true);


--
-- Name: flight_app_division_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.flight_app_division_id_seq', 5, true);


--
-- Name: flight_app_flightdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.flight_app_flightdata_id_seq', 4, true);


--
-- Name: flight_app_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.flight_app_user_groups_id_seq', 1, false);


--
-- Name: flight_app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.flight_app_user_id_seq', 4, true);


--
-- Name: flight_app_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.flight_app_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: flight_app_auditlog flight_app_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_auditlog
    ADD CONSTRAINT flight_app_auditlog_pkey PRIMARY KEY (id);


--
-- Name: flight_app_division flight_app_division_code_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_division
    ADD CONSTRAINT flight_app_division_code_key UNIQUE (code);


--
-- Name: flight_app_division flight_app_division_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_division
    ADD CONSTRAINT flight_app_division_name_key UNIQUE (name);


--
-- Name: flight_app_division flight_app_division_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_division
    ADD CONSTRAINT flight_app_division_pkey PRIMARY KEY (id);


--
-- Name: flight_app_flightdata flight_app_flightdata_date_flight_number_divis_72560a13_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_flightdata
    ADD CONSTRAINT flight_app_flightdata_date_flight_number_divis_72560a13_uniq UNIQUE (date, flight_number, division_id);


--
-- Name: flight_app_flightdata flight_app_flightdata_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_flightdata
    ADD CONSTRAINT flight_app_flightdata_pkey PRIMARY KEY (id);


--
-- Name: flight_app_user_groups flight_app_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_groups
    ADD CONSTRAINT flight_app_user_groups_pkey PRIMARY KEY (id);


--
-- Name: flight_app_user_groups flight_app_user_groups_user_id_group_id_fb3b189b_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_groups
    ADD CONSTRAINT flight_app_user_groups_user_id_group_id_fb3b189b_uniq UNIQUE (user_id, group_id);


--
-- Name: flight_app_user flight_app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user
    ADD CONSTRAINT flight_app_user_pkey PRIMARY KEY (id);


--
-- Name: flight_app_user_user_permissions flight_app_user_user_per_user_id_permission_id_3517e977_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_user_permissions
    ADD CONSTRAINT flight_app_user_user_per_user_id_permission_id_3517e977_uniq UNIQUE (user_id, permission_id);


--
-- Name: flight_app_user_user_permissions flight_app_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_user_permissions
    ADD CONSTRAINT flight_app_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: flight_app_user flight_app_user_username_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user
    ADD CONSTRAINT flight_app_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: flight_app_auditlog_user_id_f38dc09b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_auditlog_user_id_f38dc09b ON public.flight_app_auditlog USING btree (user_id);


--
-- Name: flight_app_division_code_fc4b979d_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_division_code_fc4b979d_like ON public.flight_app_division USING btree (code varchar_pattern_ops);


--
-- Name: flight_app_division_name_3dbec1d3_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_division_name_3dbec1d3_like ON public.flight_app_division USING btree (name varchar_pattern_ops);


--
-- Name: flight_app_flightdata_created_by_id_fa81de69; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_flightdata_created_by_id_fa81de69 ON public.flight_app_flightdata USING btree (created_by_id);


--
-- Name: flight_app_flightdata_division_id_0e82dc60; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_flightdata_division_id_0e82dc60 ON public.flight_app_flightdata USING btree (division_id);


--
-- Name: flight_app_user_division_id_d306675c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_user_division_id_d306675c ON public.flight_app_user USING btree (division_id);


--
-- Name: flight_app_user_groups_group_id_33d1e9a6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_user_groups_group_id_33d1e9a6 ON public.flight_app_user_groups USING btree (group_id);


--
-- Name: flight_app_user_groups_user_id_0517d7e1; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_user_groups_user_id_0517d7e1 ON public.flight_app_user_groups USING btree (user_id);


--
-- Name: flight_app_user_user_permissions_permission_id_3c1238a9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_user_user_permissions_permission_id_3c1238a9 ON public.flight_app_user_user_permissions USING btree (permission_id);


--
-- Name: flight_app_user_user_permissions_user_id_d0d2bc77; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_user_user_permissions_user_id_d0d2bc77 ON public.flight_app_user_user_permissions USING btree (user_id);


--
-- Name: flight_app_user_username_540c8512_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX flight_app_user_username_540c8512_like ON public.flight_app_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_flight_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_flight_app_user_id FOREIGN KEY (user_id) REFERENCES public.flight_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_auditlog flight_app_auditlog_user_id_f38dc09b_fk_flight_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_auditlog
    ADD CONSTRAINT flight_app_auditlog_user_id_f38dc09b_fk_flight_app_user_id FOREIGN KEY (user_id) REFERENCES public.flight_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_flightdata flight_app_flightdat_created_by_id_fa81de69_fk_flight_ap; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_flightdata
    ADD CONSTRAINT flight_app_flightdat_created_by_id_fa81de69_fk_flight_ap FOREIGN KEY (created_by_id) REFERENCES public.flight_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_flightdata flight_app_flightdat_division_id_0e82dc60_fk_flight_ap; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_flightdata
    ADD CONSTRAINT flight_app_flightdat_division_id_0e82dc60_fk_flight_ap FOREIGN KEY (division_id) REFERENCES public.flight_app_division(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_user flight_app_user_division_id_d306675c_fk_flight_app_division_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user
    ADD CONSTRAINT flight_app_user_division_id_d306675c_fk_flight_app_division_id FOREIGN KEY (division_id) REFERENCES public.flight_app_division(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_user_groups flight_app_user_groups_group_id_33d1e9a6_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_groups
    ADD CONSTRAINT flight_app_user_groups_group_id_33d1e9a6_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_user_groups flight_app_user_groups_user_id_0517d7e1_fk_flight_app_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_groups
    ADD CONSTRAINT flight_app_user_groups_user_id_0517d7e1_fk_flight_app_user_id FOREIGN KEY (user_id) REFERENCES public.flight_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_user_user_permissions flight_app_user_user_permission_id_3c1238a9_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_user_permissions
    ADD CONSTRAINT flight_app_user_user_permission_id_3c1238a9_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight_app_user_user_permissions flight_app_user_user_user_id_d0d2bc77_fk_flight_ap; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.flight_app_user_user_permissions
    ADD CONSTRAINT flight_app_user_user_user_id_d0d2bc77_fk_flight_ap FOREIGN KEY (user_id) REFERENCES public.flight_app_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

