# Generated by Django 5.1.7 on 2025-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('foi_fod', 'FOI/FOD'), ('ccd', 'CCD'), ('oep', 'OEP'), ('of', 'OF')], default='user', max_length=20),
        ),
    ]
