# Generated by Django 5.1.7 on 2025-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='afl_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='air_time_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='air_time_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='block_time_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='block_time_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='cargo_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_added_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_burnt_tons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_uplift_liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='mail_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='pax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='remaining_fuel_tons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='sp_gravity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_fuel_tons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
