# Generated by Django 5.1.7 on 2025-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
